on: push
name: build file
jobs:
  web-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@master

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Build Project
      run: |
        yarn install
        yarn build
